package cn.mapway.globe.server.gabage;

public  class Colors  {
    public static Color get(String colorName)
    {
        switch (colorName) {
            case "black": return BLACK;
            case "blanchedalmond": return BLANCHEDALMOND;
            case "blue": return BLUE;
            case "blueviolet": return BLUEVIOLET;
            case "brown": return BROWN;
            case "burlywood": return BURLYWOOD;
            case "cadetblue": return CADETBLUE;
            case "chartreuse": return CHARTREUSE;
            case "chocolate": return CHOCOLATE;
            case "coral": return CORAL;
            case "cornflowerblue": return CORNFLOWERBLUE;
            case "cornsilk": return CORNSILK;
            case "crimson": return CRIMSON;
            case "cyan": return CYAN;
            case "darkblue": return DARKBLUE;
            case "darkcyan": return DARKCYAN;
            case "darkgoldenrod": return DARKGOLDENROD;
            case "darkgray": return DARKGRAY;
            case "darkgreen": return DARKGREEN;
            case "darkgrey": return DARKGREY;
            case "darkkhaki": return DARKKHAKI;
            case "darkmagenta": return DARKMAGENTA;
            case "darkolivegreen": return DARKOLIVEGREEN;
            case "darkorange": return DARKORANGE;
            case "darkorchid": return DARKORCHID;
            case "darkred": return DARKRED;
            case "darksalmon": return DARKSALMON;
            case "darkseagreen": return DARKSEAGREEN;
            case "darkslateblue": return DARKSLATEBLUE;
            case "darkslategray": return DARKSLATEGRAY;
            case "darkslategrey": return DARKSLATEGREY;
            case "darkturquoise": return DARKTURQUOISE;
            case "darkviolet": return DARKVIOLET;
            case "deeppink": return DEEPPINK;
            case "deepskyblue": return DEEPSKYBLUE;
            case "dimgray": return DIMGRAY;
            case "dimgrey": return DIMGREY;
            case "dodgerblue": return DODGERBLUE;
            case "firebrick": return FIREBRICK;
            case "floralwhite": return FLORALWHITE;
            case "forestgreen": return FORESTGREEN;
            case "fuchsia": return FUCHSIA;
            case "gainsboro": return GAINSBORO;
            case "ghostwhite": return GHOSTWHITE;
            case "gold": return GOLD;
            case "goldenrod": return GOLDENROD;
            case "gray": return GRAY;
            case "green": return GREEN;
            case "greenyellow": return GREENYELLOW;
            case "grey": return GREY;
            case "honeydew": return HONEYDEW;
            case "hotpink": return HOTPINK;
            case "indianred": return INDIANRED;
            case "indigo": return INDIGO;
            case "ivory": return IVORY;
            case "khaki": return KHAKI;
            case "lavender": return LAVENDER;
            case "lavenderblush": return LAVENDERBLUSH;
            case "lawngreen": return LAWNGREEN;
            case "lemonchiffon": return LEMONCHIFFON;
            case "lightblue": return LIGHTBLUE;
            case "lightcoral": return LIGHTCORAL;
            case "lightcyan": return LIGHTCYAN;
            case "lightgoldenrodyellow": return LIGHTGOLDENRODYELLOW;
            case "lightgray": return LIGHTGRAY;
            case "lightgreen": return LIGHTGREEN;
            case "lightgrey": return LIGHTGREY;
            case "lightpink": return LIGHTPINK;
            case "lightsalmon": return LIGHTSALMON;
            case "lightseagreen": return LIGHTSEAGREEN;
            case "lightskyblue": return LIGHTSKYBLUE;
            case "lightslategray": return LIGHTSLATEGRAY;
            case "lightslategrey": return LIGHTSLATEGREY;
            case "lightsteelblue": return LIGHTSTEELBLUE;
            case "lightyellow": return LIGHTYELLOW;
            case "lime": return LIME;
            case "limegreen": return LIMEGREEN;
            case "linen": return LINEN;
            case "magenta": return MAGENTA;
            case "maroon": return MAROON;
            case "mediumaquamarine": return MEDIUMAQUAMARINE;
            case "mediumblue": return MEDIUMBLUE;
            case "mediumorchid": return MEDIUMORCHID;
            case "mediumpurple": return MEDIUMPURPLE;
            case "mediumseagreen": return MEDIUMSEAGREEN;
            case "mediumslateblue": return MEDIUMSLATEBLUE;
            case "mediumspringgreen": return MEDIUMSPRINGGREEN;
            case "mediumturquoise": return MEDIUMTURQUOISE;
            case "mediumvioletred": return MEDIUMVIOLETRED;
            case "midnightblue": return MIDNIGHTBLUE;
            case "mintcream": return MINTCREAM;
            case "mistyrose": return MISTYROSE;
            case "moccasin": return MOCCASIN;
            case "navajowhite": return NAVAJOWHITE;
            case "navy": return NAVY;
            case "oldlace": return OLDLACE;
            case "olive": return OLIVE;
            case "olivedrab": return OLIVEDRAB;
            case "orange": return ORANGE;
            case "orangered": return ORANGERED;
            case "orchid": return ORCHID;
            case "palegoldenrod": return PALEGOLDENROD;
            case "palegreen": return PALEGREEN;
            case "paleturquoise": return PALETURQUOISE;
            case "palevioletred": return PALEVIOLETRED;
            case "papayawhip": return PAPAYAWHIP;
            case "peachpuff": return PEACHPUFF;
            case "peru": return PERU;
            case "pink": return PINK;
            case "plum": return PLUM;
            case "powderblue": return POWDERBLUE;
            case "purple": return PURPLE;
            case "rebeccapurple": return REBECCAPURPLE;
            case "red": return RED;
            case "rosybrown": return ROSYBROWN;
            case "royalblue": return ROYALBLUE;
            case "saddlebrown": return SADDLEBROWN;
            case "salmon": return SALMON;
            case "sandybrown": return SANDYBROWN;
            case "seagreen": return SEAGREEN;
            case "seashell": return SEASHELL;
            case "sienna": return SIENNA;
            case "silver": return SILVER;
            case "skyblue": return SKYBLUE;
            case "slateblue": return SLATEBLUE;
            case "slategray": return SLATEGRAY;
            case "slategrey": return SLATEGREY;
            case "snow": return SNOW;
            case "springgreen": return SPRINGGREEN;
            case "steelblue": return STEELBLUE;
            case "tan": return TAN;
            case "teal": return TEAL;
            case "thistle": return THISTLE;
            case "tomato": return TOMATO;
            case "turquoise": return TURQUOISE;
            case "violet": return VIOLET;
            case "wheat": return WHEAT;
            case "white": return WHITE;
            case "whitesmoke": return WHITESMOKE;
            case "yellow": return YELLOW;
            case "yellowgreen": return YELLOWGREEN;
            case "transparent":
            default: return TRANSPARENT;
        }
    }
    public static final Color BLACK= Color.fromCssColorString("#000000");
    public static final Color BLANCHEDALMOND= Color.fromCssColorString("#FFEBCD");
    public static final Color BLUE= Color.fromCssColorString("#0000FF");
    public static final Color BLUEVIOLET= Color.fromCssColorString("#8A2BE2");
    public static final Color BROWN= Color.fromCssColorString("#A52A2A");
    public static final Color BURLYWOOD= Color.fromCssColorString("#DEB887");
    public static final Color CADETBLUE= Color.fromCssColorString("#5F9EA0");
    public static final Color CHARTREUSE= Color.fromCssColorString("#7FFF00");
    public static final Color CHOCOLATE= Color.fromCssColorString("#D2691E");
    public static final Color CORAL= Color.fromCssColorString("#FF7F50");
    public static final Color CORNFLOWERBLUE= Color.fromCssColorString("#6495ED");
    public static final Color CORNSILK= Color.fromCssColorString("#FFF8DC");
    public static final Color CRIMSON= Color.fromCssColorString("#DC143C");
    public static final Color CYAN= Color.fromCssColorString("#00FFFF");
    public static final Color DARKBLUE= Color.fromCssColorString("#00008B");
    public static final Color DARKCYAN= Color.fromCssColorString("#008B8B");
    public static final Color DARKGOLDENROD= Color.fromCssColorString("#B8860B");
    public static final Color DARKGRAY= Color.fromCssColorString("#A9A9A9");
    public static final Color DARKGREEN= Color.fromCssColorString("#006400");
    public static final Color DARKGREY= Color.fromCssColorString("#A9A9A9");
    public static final Color DARKKHAKI= Color.fromCssColorString("#BDB76B");
    public static final Color DARKMAGENTA= Color.fromCssColorString("#8B008B");
    public static final Color DARKOLIVEGREEN= Color.fromCssColorString("#556B2F");
    public static final Color DARKORANGE= Color.fromCssColorString("#FF8C00");
    public static final Color DARKORCHID= Color.fromCssColorString("#9932CC");
    public static final Color DARKRED= Color.fromCssColorString("#8B0000");
    public static final Color DARKSALMON= Color.fromCssColorString("#E9967A");
    public static final Color DARKSEAGREEN= Color.fromCssColorString("#8FBC8F");
    public static final Color DARKSLATEBLUE= Color.fromCssColorString("#483D8B");
    public static final Color DARKSLATEGRAY= Color.fromCssColorString("#2F4F4F");
    public static final Color DARKSLATEGREY= Color.fromCssColorString("#2F4F4F");
    public static final Color DARKTURQUOISE= Color.fromCssColorString("#00CED1");
    public static final Color DARKVIOLET= Color.fromCssColorString("#9400D3");
    public static final Color DEEPPINK= Color.fromCssColorString("#FF1493");
    public static final Color DEEPSKYBLUE= Color.fromCssColorString("#00BFFF");
    public static final Color DIMGRAY= Color.fromCssColorString("#696969");
    public static final Color DIMGREY= Color.fromCssColorString("#696969");
    public static final Color DODGERBLUE= Color.fromCssColorString("#1E90FF");
    public static final Color FIREBRICK= Color.fromCssColorString("#B22222");
    public static final Color FLORALWHITE= Color.fromCssColorString("#FFFAF0");
    public static final Color FORESTGREEN= Color.fromCssColorString("#228B22");
    public static final Color FUCHSIA= Color.fromCssColorString("#FF00FF");
    public static final Color GAINSBORO= Color.fromCssColorString("#DCDCDC");
    public static final Color GHOSTWHITE= Color.fromCssColorString("#F8F8FF");
    public static final Color GOLD= Color.fromCssColorString("#FFD700");
    public static final Color GOLDENROD= Color.fromCssColorString("#DAA520");
    public static final Color GRAY= Color.fromCssColorString("#808080");
    public static final Color GREEN= Color.fromCssColorString("#008000");
    public static final Color GREENYELLOW= Color.fromCssColorString("#ADFF2F");
    public static final Color GREY= Color.fromCssColorString("#808080");
    public static final Color HONEYDEW= Color.fromCssColorString("#F0FFF0");
    public static final Color HOTPINK= Color.fromCssColorString("#FF69B4");
    public static final Color INDIANRED= Color.fromCssColorString("#CD5C5C");
    public static final Color INDIGO= Color.fromCssColorString("#4B0082");
    public static final Color IVORY= Color.fromCssColorString("#FFFFF0");
    public static final Color KHAKI= Color.fromCssColorString("#F0E68C");
    public static final Color LAVENDER= Color.fromCssColorString("#E6E6FA");
    public static final Color LAVENDERBLUSH= Color.fromCssColorString("#FFF0F5");
    public static final Color LEMONCHIFFON= Color.fromCssColorString("#FFFACD");
    public static final Color LIGHTBLUE= Color.fromCssColorString("#ADD8E6");
    public static final Color LIGHTCORAL= Color.fromCssColorString("#F08080");
    public static final Color LIGHTCYAN= Color.fromCssColorString("#E0FFFF");
    public static final Color LIGHTGOLDENRODYELLOW= Color.fromCssColorString("#FAFAD2");
    public static final Color LIGHTGRAY= Color.fromCssColorString("#D3D3D3");
    public static final Color LIGHTGREEN= Color.fromCssColorString("#90EE90");
    public static final Color LIGHTGREY= Color.fromCssColorString("#D3D3D3");
    public static final Color LIGHTPINK= Color.fromCssColorString("#FFB6C1");
    public static final Color LIGHTSALMON= Color.fromCssColorString("#FFA07A");
    public static final Color LIGHTSEAGREEN= Color.fromCssColorString("#20B2AA");
    public static final Color LIGHTSKYBLUE= Color.fromCssColorString("#87CEFA");
    public static final Color LIGHTSLATEGRAY= Color.fromCssColorString("#778899");
    public static final Color LIGHTSLATEGREY= Color.fromCssColorString("#778899");
    public static final Color LIGHTSTEELBLUE= Color.fromCssColorString("#B0C4DE");
    public static final Color LIGHTYELLOW= Color.fromCssColorString("#FFFFE0");
    public static final Color LIME= Color.fromCssColorString("#00FF00");
    public static final Color LIMEGREEN= Color.fromCssColorString("#32CD32");
    public static final Color LINEN= Color.fromCssColorString("#FAF0E6");
    public static final Color MAGENTA= Color.fromCssColorString("#FF00FF");
    public static final Color MAROON= Color.fromCssColorString("#800000");
    public static final Color MEDIUMAQUAMARINE= Color.fromCssColorString("#66CDAA");
    public static final Color MEDIUMBLUE= Color.fromCssColorString("#0000CD");
    public static final Color MEDIUMORCHID= Color.fromCssColorString("#BA55D3");
    public static final Color MEDIUMPURPLE= Color.fromCssColorString("#9370DB");
    public static final Color MEDIUMSEAGREEN= Color.fromCssColorString("#3CB371");
    public static final Color MEDIUMSLATEBLUE= Color.fromCssColorString("#7B68EE");
    public static final Color MEDIUMSPRINGGREEN= Color.fromCssColorString("#00FA9A");
    public static final Color MEDIUMTURQUOISE= Color.fromCssColorString("#48D1CC");
    public static final Color MEDIUMVIOLETRED= Color.fromCssColorString("#C71585");
    public static final Color MIDNIGHTBLUE= Color.fromCssColorString("#191970");
    public static final Color MINTCREAM= Color.fromCssColorString("#F5FFFA");
    public static final Color MISTYROSE= Color.fromCssColorString("#FFE4E1");
    public static final Color MOCCASIN= Color.fromCssColorString("#FFE4B5");
    public static final Color NAVAJOWHITE= Color.fromCssColorString("#FFDEAD");
    public static final Color NAVY= Color.fromCssColorString("#000080");
    public static final Color OLDLACE= Color.fromCssColorString("#FDF5E6");
    public static final Color OLIVE= Color.fromCssColorString("#808000");
    public static final Color OLIVEDRAB= Color.fromCssColorString("#6B8E23");
    public static final Color ORANGE= Color.fromCssColorString("#FFA500");
    public static final Color ORANGERED= Color.fromCssColorString("#FF4500");
    public static final Color ORCHID= Color.fromCssColorString("#DA70D6");
    public static final Color PALEGOLDENROD= Color.fromCssColorString("#EEE8AA");
    public static final Color PALEGREEN= Color.fromCssColorString("#98FB98");
    public static final Color PALETURQUOISE= Color.fromCssColorString("#AFEEEE");
    public static final Color PALEVIOLETRED= Color.fromCssColorString("#DB7093");
    public static final Color PAPAYAWHIP= Color.fromCssColorString("#FFEFD5");
    public static final Color PEACHPUFF= Color.fromCssColorString("#FFDAB9");
    public static final Color PERU= Color.fromCssColorString("#CD853F");
    public static final Color PINK= Color.fromCssColorString("#FFC0CB");
    public static final Color PLUM= Color.fromCssColorString("#DDA0DD");
    public static final Color POWDERBLUE= Color.fromCssColorString("#B0E0E6");
    public static final Color PURPLE= Color.fromCssColorString("#800080");
    public static final Color RED= Color.fromCssColorString("#FF0000");
    public static final Color ROSYBROWN= Color.fromCssColorString("#BC8F8F");
    public static final Color ROYALBLUE= Color.fromCssColorString("#4169E1");
    public static final Color SADDLEBROWN= Color.fromCssColorString("#8B4513");
    public static final Color SALMON= Color.fromCssColorString("#FA8072");
    public static final Color SANDYBROWN= Color.fromCssColorString("#F4A460");
    public static final Color SEAGREEN= Color.fromCssColorString("#2E8B57");
    public static final Color SEASHELL= Color.fromCssColorString("#FFF5EE");
    public static final Color SIENNA= Color.fromCssColorString("#A0522D");
    public static final Color SILVER= Color.fromCssColorString("#C0C0C0");
    public static final Color SKYBLUE= Color.fromCssColorString("#87CEEB");
    public static final Color SLATEBLUE= Color.fromCssColorString("#6A5ACD");
    public static final Color SLATEGRAY= Color.fromCssColorString("#708090");
    public static final Color SLATEGREY= Color.fromCssColorString("#708090");
    public static final Color SNOW= Color.fromCssColorString("#FFFAFA");
    public static final Color SPRINGGREEN= Color.fromCssColorString("#00FF7F");
    public static final Color STEELBLUE= Color.fromCssColorString("#4682B4");
    public static final Color TAN= Color.fromCssColorString("#D2B48C");
    public static final Color TEAL= Color.fromCssColorString("#008080");
    public static final Color THISTLE= Color.fromCssColorString("#D8BFD8");
    public static final Color TOMATO= Color.fromCssColorString("#FF6347");
    public static final Color TURQUOISE= Color.fromCssColorString("#40E0D0");
    public static final Color VIOLET= Color.fromCssColorString("#EE82EE");
    public static final Color WHEAT= Color.fromCssColorString("#F5DEB3");
    public static final Color WHITE= Color.fromCssColorString("#FFFFFF");
    public static final Color WHITESMOKE= Color.fromCssColorString("#F5F5F5");
    public static final Color YELLOW= Color.fromCssColorString("#FFFF00");
    public static final Color YELLOWGREEN= Color.fromCssColorString("#9ACD32");
    public static final Color REBECCAPURPLE= Color.fromCssColorString("#663399");
    public static final Color LAWNGREEN= Color.fromCssColorString("#7CFC00");
    public static final Color TRANSPARENT= Color.create(0,0,0,0);

}
