package cn.mapway.ui.client.fonts;
import java.util.HashMap;
import java.util.Map;
/**
 * Fonts
 * 图标字体常量
 * @author zhang
 */
public class Fonts {
    public static String toHtmlEntity(String fontIndex){
        return "&#x"+fontIndex;
    }
    	public final static String FUZHI = "e6c7";
	public final static String NIANTIE = "e6c9";
	public final static String RABBITMQ_LOGO_SVGREPO_COM = "e6c5";
	public final static String PROJECT = "e6c4";
	public final static String ZHUANHUAN = "e6c8";
	public final static String XUANZE = "e61c";
	public final static String CAMERA = "e6c6";
	public final static String SEARCHABLE = "e6c3";
	public final static String ALERT1 = "e6c1";
	public final static String TABLE = "e6c2";
	public final static String SERIAL = "e6c0";
	public final static String INT8 = "e6bf";
	public final static String UNKNOWN = "e6be";
	public final static String GEO_COLLECTION = "e6bd";
	public final static String LINE = "e6b7";
	public final static String POINT = "e6b8";
	public final static String POLYGON = "e6b9";
	public final static String LINES = "e6ba";
	public final static String POINTS = "e6bb";
	public final static String POLYGONS = "e6bc";
	public final static String POSTGIS = "e6b6";
	public final static String CATEGORY_PLUS = "e6b5";
	public final static String SHIELD_INFO = "e6b4";
	public final static String CATALOG = "e6b3";
	public final static String MOVE = "e6b2";
	public final static String WORKSPACE = "e66e";
	public final static String MULTI_SELECT = "e6b1";
	public final static String RENAME = "e6af";
	public final static String SELECTED = "e6b0";
	public final static String APPS = "e6ae";
	public final static String UPLOAD_BIG = "e6ac";
	public final static String UPLOAD_SMALL = "e6ad";
	public final static String ACCOUNT = "e6ab";
	public final static String IMAGE = "e6a9";
	public final static String SHAPES = "e6aa";
	public final static String MAP_BORDER = "e6a8";
	public final static String PIN_FILL = "e6a7";
	public final static String RS = "e6a6";
	public final static String TIP = "e6a5";
	public final static String ERROR = "e6a4";
	public final static String PREPARE = "e6a3";
	public final static String MAP_CONFIG = "e6a1";
	public final static String UI_CONFIG = "e6a2";
	public final static String IB = "e6a0";
	public final static String IMAGEBOT = "e69f";
	public final static String EXIT = "e69e";
	public final static String THIRD_PARTY = "e69d";
	public final static String STATISTIC = "e69c";
	public final static String SORT_ASCENDING = "e699";
	public final static String SORT_VARIANT = "e69a";
	public final static String SORT_DESCENDING = "e69b";
	public final static String MAP_SEARCH = "e698";
	public final static String QUEUE = "e697";
	public final static String PAUSEING = "e689";
	public final static String RUNNING = "e68a";
	public final static String STOP = "e695";
	public final static String STOPPING = "e696";
	public final static String NUMBER = "e685";
	public final static String TEXTFORMAT_123 = "e692";
	public final static String CALENDAR = "e693";
	public final static String ABC = "e694";
	public final static String KEY = "e683";
	public final static String CLOSE_L = "e684";
	public final static String CONTROLER = "e686";
	public final static String FIRE = "e687";
	public final static String MOVABLE = "e688";
	public final static String MORE = "e68b";
	public final static String SORT1 = "e68c";
	public final static String DESIGN = "e68d";
	public final static String ON = "e68e";
	public final static String CLOSE1 = "e68f";
	public final static String REMOVE = "e690";
	public final static String OFF = "e691";
	public final static String ZHONG = "e682";
	public final static String OPEN = "e681";
	public final static String DEVELOPER = "e680";
	public final static String SCHEMA_PROPERTY = "e67f";
	public final static String WARNING = "e67e";
	public final static String STYLE = "e67d";
	public final static String OVERVIEW = "e67c";
	public final static String PRODUCT = "e66c";
	public final static String LAND = "e672";
	public final static String CHEMETRY = "e673";
	public final static String RESIDENT = "e674";
	public final static String ROAD = "e675";
	public final static String FIRE_ENERGY = "e676";
	public final static String DAPENG = "e677";
	public final static String TANK = "e678";
	public final static String WEI_MINER = "e679";
	public final static String WATER_ENERGY = "e67a";
	public final static String WATER_FARM = "e67b";
	public final static String FE = "e670";
	public final static String BUILDING = "e671";
	public final static String EME_TEXT = "e66f";
	public final static String LABEL_MAKER = "e66d";
	public final static String CONTRAST = "e66b";
	public final static String MODULE = "e66a";
	public final static String ALIGN_VERTICAL = "e668";
	public final static String ALIGN_HORIZONTAL = "e669";
	public final static String ALIGN_BOTTOM = "e660";
	public final static String ALIGN_LEFT = "e661";
	public final static String ALIGN_CENTER = "e662";
	public final static String ALIGN_RIGHT = "e663";
	public final static String TEXT_WRAP = "e664";
	public final static String ALIGN_MIDDLE = "e665";
	public final static String LIST = "e666";
	public final static String ALIGN_TOP = "e667";
	public final static String HELP = "e65f";
	public final static String APPLICATION = "e65e";
	public final static String IMAGESTUDIO = "e65d";
	public final static String PLOTTING = "e65c";
	public final static String SCHEMA = "e656";
	public final static String FLOW = "e65b";
	public final static String CLEAN_SAMPLE = "e65a";
	public final static String SAMPLE_PRODUCT = "e659";
	public final static String SAMPLE_PLOTTING = "e658";
	public final static String IMPORT_SAMPLE = "e657";
	public final static String TOOLBOX = "e64f";
	public final static String HYPERFRACTIONATION = "e655";
	public final static String ENHANCE_COLOR = "e654";
	public final static String CLOUD_DETECTION = "e653";
	public final static String ORTHOPHOTO = "e652";
	public final static String LAYOUT = "e650";
	public final static String CREATE = "e651";
	public final static String ADD_PROJECT = "e64e";
	public final static String LAYER_MANAGEMENT = "e64d";
	public final static String FAVORITE_ON = "e64c";
	public final static String FAVORITE_OFF = "e64b";
	public final static String TRAININGSTUDIO = "e64a";
	public final static String MAPSTUDIO = "e649";
	public final static String LABELFACTORY = "e606";
	public final static String AISTUDIO = "e600";
	public final static String ADMIN = "e6ed";
	public final static String GRID = "e648";
	public final static String EARTH = "e647";
	public final static String LINK = "e646";
	public final static String WRITE = "e645";
	public final static String READ = "e644";
	public final static String VISIBILITY = "e639";
	public final static String HIDDEN = "e63a";
	public final static String PALETTE = "e643";
	public final static String RETURN = "e63f";
	public final static String TERMINAL = "e640";
	public final static String SHARE = "e641";
	public final static String LOG = "e642";
	public final static String TASK = "e63b";
	public final static String FEATURE = "e63c";
	public final static String OBJECT = "e63d";
	public final static String MODEL = "e63e";
	public final static String ROLL = "e631";
	public final static String LAYERS = "e632";
	public final static String MAP_ADD = "e633";
	public final static String DELETE = "e634";
	public final static String LOCATION = "e635";
	public final static String RESET = "e636";
	public final static String CATALOG_ADD = "e637";
	public final static String COMPARE = "e638";
	public final static String LEGEND = "e630";
	public final static String CERT = "e62c";
	public final static String METADATA = "e62e";
	public final static String K8S = "e62f";
	public final static String SAVE = "e62b";
	public final static String LOGO = "e62a";
	public final static String PROCESS = "e628";
	public final static String CANGLING_TEXT = "e629";
	public final static String GEOSERVER = "e626";
	public final static String LABEL = "e627";
	public final static String LIGHTMODE = "e624";
	public final static String DARKMODE = "e625";
	public final static String GEOTRELLIS = "e623";
	public final static String FOLDER_FILE = "e622";
	public final static String PLAY = "e620";
	public final static String PAUSE = "e621";
	public final static String FILES = "e61f";
	public final static String IMAGES = "e61e";
	public final static String CLEAR_CACHE = "e61d";
	public final static String ALERT = "e61b";
	public final static String SFILE = "e61a";
	public final static String FOLDER = "e618";
	public final static String FILE = "e619";
	public final static String LEFT = "e616";
	public final static String RIGHT = "e617";
	public final static String DOWN = "e614";
	public final static String UP = "e615";
	public final static String REFRESH = "e613";
	public final static String INFO = "e610";
	public final static String COLORS = "e611";
	public final static String CLEAR = "e612";
	public final static String DONE = "e60f";
	public final static String FULL_SCREEN = "e60c";
	public final static String HARBOR = "e60d";
	public final static String PLUS = "e60e";
	public final static String UPLOAD = "e60a";
	public final static String DOWNLOAD = "e60b";
	public final static String DOUBLE_LEFT = "e608";
	public final static String DOUBLE_RIGHT = "e609";
	public final static String FINANCIAL_HARD_DISK = "e607";
	public final static String SEARCH = "e604";
	public final static String SETTING = "e602";
	public final static String CONSOLE = "e601";

   public static Map<String,String> unicodes;
	static {
		unicodes=new HashMap<>();
		//unicodes.put("console", Fonts.CONSOLE);
			unicodes.put("FUZHI", Fonts.FUZHI);
	unicodes.put("NIANTIE", Fonts.NIANTIE);
	unicodes.put("RABBITMQ_LOGO_SVGREPO_COM", Fonts.RABBITMQ_LOGO_SVGREPO_COM);
	unicodes.put("PROJECT", Fonts.PROJECT);
	unicodes.put("ZHUANHUAN", Fonts.ZHUANHUAN);
	unicodes.put("XUANZE", Fonts.XUANZE);
	unicodes.put("CAMERA", Fonts.CAMERA);
	unicodes.put("SEARCHABLE", Fonts.SEARCHABLE);
	unicodes.put("ALERT1", Fonts.ALERT1);
	unicodes.put("TABLE", Fonts.TABLE);
	unicodes.put("SERIAL", Fonts.SERIAL);
	unicodes.put("INT8", Fonts.INT8);
	unicodes.put("UNKNOWN", Fonts.UNKNOWN);
	unicodes.put("GEO_COLLECTION", Fonts.GEO_COLLECTION);
	unicodes.put("LINE", Fonts.LINE);
	unicodes.put("POINT", Fonts.POINT);
	unicodes.put("POLYGON", Fonts.POLYGON);
	unicodes.put("LINES", Fonts.LINES);
	unicodes.put("POINTS", Fonts.POINTS);
	unicodes.put("POLYGONS", Fonts.POLYGONS);
	unicodes.put("POSTGIS", Fonts.POSTGIS);
	unicodes.put("CATEGORY_PLUS", Fonts.CATEGORY_PLUS);
	unicodes.put("SHIELD_INFO", Fonts.SHIELD_INFO);
	unicodes.put("CATALOG", Fonts.CATALOG);
	unicodes.put("MOVE", Fonts.MOVE);
	unicodes.put("WORKSPACE", Fonts.WORKSPACE);
	unicodes.put("MULTI_SELECT", Fonts.MULTI_SELECT);
	unicodes.put("RENAME", Fonts.RENAME);
	unicodes.put("SELECTED", Fonts.SELECTED);
	unicodes.put("APPS", Fonts.APPS);
	unicodes.put("UPLOAD_BIG", Fonts.UPLOAD_BIG);
	unicodes.put("UPLOAD_SMALL", Fonts.UPLOAD_SMALL);
	unicodes.put("ACCOUNT", Fonts.ACCOUNT);
	unicodes.put("IMAGE", Fonts.IMAGE);
	unicodes.put("SHAPES", Fonts.SHAPES);
	unicodes.put("MAP_BORDER", Fonts.MAP_BORDER);
	unicodes.put("PIN_FILL", Fonts.PIN_FILL);
	unicodes.put("RS", Fonts.RS);
	unicodes.put("TIP", Fonts.TIP);
	unicodes.put("ERROR", Fonts.ERROR);
	unicodes.put("PREPARE", Fonts.PREPARE);
	unicodes.put("MAP_CONFIG", Fonts.MAP_CONFIG);
	unicodes.put("UI_CONFIG", Fonts.UI_CONFIG);
	unicodes.put("IB", Fonts.IB);
	unicodes.put("IMAGEBOT", Fonts.IMAGEBOT);
	unicodes.put("EXIT", Fonts.EXIT);
	unicodes.put("THIRD_PARTY", Fonts.THIRD_PARTY);
	unicodes.put("STATISTIC", Fonts.STATISTIC);
	unicodes.put("SORT_ASCENDING", Fonts.SORT_ASCENDING);
	unicodes.put("SORT_VARIANT", Fonts.SORT_VARIANT);
	unicodes.put("SORT_DESCENDING", Fonts.SORT_DESCENDING);
	unicodes.put("MAP_SEARCH", Fonts.MAP_SEARCH);
	unicodes.put("QUEUE", Fonts.QUEUE);
	unicodes.put("PAUSEING", Fonts.PAUSEING);
	unicodes.put("RUNNING", Fonts.RUNNING);
	unicodes.put("STOP", Fonts.STOP);
	unicodes.put("STOPPING", Fonts.STOPPING);
	unicodes.put("NUMBER", Fonts.NUMBER);
	unicodes.put("TEXTFORMAT_123", Fonts.TEXTFORMAT_123);
	unicodes.put("CALENDAR", Fonts.CALENDAR);
	unicodes.put("ABC", Fonts.ABC);
	unicodes.put("KEY", Fonts.KEY);
	unicodes.put("CLOSE_L", Fonts.CLOSE_L);
	unicodes.put("CONTROLER", Fonts.CONTROLER);
	unicodes.put("FIRE", Fonts.FIRE);
	unicodes.put("MOVABLE", Fonts.MOVABLE);
	unicodes.put("MORE", Fonts.MORE);
	unicodes.put("SORT1", Fonts.SORT1);
	unicodes.put("DESIGN", Fonts.DESIGN);
	unicodes.put("ON", Fonts.ON);
	unicodes.put("CLOSE1", Fonts.CLOSE1);
	unicodes.put("REMOVE", Fonts.REMOVE);
	unicodes.put("OFF", Fonts.OFF);
	unicodes.put("ZHONG", Fonts.ZHONG);
	unicodes.put("OPEN", Fonts.OPEN);
	unicodes.put("DEVELOPER", Fonts.DEVELOPER);
	unicodes.put("SCHEMA_PROPERTY", Fonts.SCHEMA_PROPERTY);
	unicodes.put("WARNING", Fonts.WARNING);
	unicodes.put("STYLE", Fonts.STYLE);
	unicodes.put("OVERVIEW", Fonts.OVERVIEW);
	unicodes.put("PRODUCT", Fonts.PRODUCT);
	unicodes.put("LAND", Fonts.LAND);
	unicodes.put("CHEMETRY", Fonts.CHEMETRY);
	unicodes.put("RESIDENT", Fonts.RESIDENT);
	unicodes.put("ROAD", Fonts.ROAD);
	unicodes.put("FIRE_ENERGY", Fonts.FIRE_ENERGY);
	unicodes.put("DAPENG", Fonts.DAPENG);
	unicodes.put("TANK", Fonts.TANK);
	unicodes.put("WEI_MINER", Fonts.WEI_MINER);
	unicodes.put("WATER_ENERGY", Fonts.WATER_ENERGY);
	unicodes.put("WATER_FARM", Fonts.WATER_FARM);
	unicodes.put("FE", Fonts.FE);
	unicodes.put("BUILDING", Fonts.BUILDING);
	unicodes.put("EME_TEXT", Fonts.EME_TEXT);
	unicodes.put("LABEL_MAKER", Fonts.LABEL_MAKER);
	unicodes.put("CONTRAST", Fonts.CONTRAST);
	unicodes.put("MODULE", Fonts.MODULE);
	unicodes.put("ALIGN_VERTICAL", Fonts.ALIGN_VERTICAL);
	unicodes.put("ALIGN_HORIZONTAL", Fonts.ALIGN_HORIZONTAL);
	unicodes.put("ALIGN_BOTTOM", Fonts.ALIGN_BOTTOM);
	unicodes.put("ALIGN_LEFT", Fonts.ALIGN_LEFT);
	unicodes.put("ALIGN_CENTER", Fonts.ALIGN_CENTER);
	unicodes.put("ALIGN_RIGHT", Fonts.ALIGN_RIGHT);
	unicodes.put("TEXT_WRAP", Fonts.TEXT_WRAP);
	unicodes.put("ALIGN_MIDDLE", Fonts.ALIGN_MIDDLE);
	unicodes.put("LIST", Fonts.LIST);
	unicodes.put("ALIGN_TOP", Fonts.ALIGN_TOP);
	unicodes.put("HELP", Fonts.HELP);
	unicodes.put("APPLICATION", Fonts.APPLICATION);
	unicodes.put("IMAGESTUDIO", Fonts.IMAGESTUDIO);
	unicodes.put("PLOTTING", Fonts.PLOTTING);
	unicodes.put("SCHEMA", Fonts.SCHEMA);
	unicodes.put("FLOW", Fonts.FLOW);
	unicodes.put("CLEAN_SAMPLE", Fonts.CLEAN_SAMPLE);
	unicodes.put("SAMPLE_PRODUCT", Fonts.SAMPLE_PRODUCT);
	unicodes.put("SAMPLE_PLOTTING", Fonts.SAMPLE_PLOTTING);
	unicodes.put("IMPORT_SAMPLE", Fonts.IMPORT_SAMPLE);
	unicodes.put("TOOLBOX", Fonts.TOOLBOX);
	unicodes.put("HYPERFRACTIONATION", Fonts.HYPERFRACTIONATION);
	unicodes.put("ENHANCE_COLOR", Fonts.ENHANCE_COLOR);
	unicodes.put("CLOUD_DETECTION", Fonts.CLOUD_DETECTION);
	unicodes.put("ORTHOPHOTO", Fonts.ORTHOPHOTO);
	unicodes.put("LAYOUT", Fonts.LAYOUT);
	unicodes.put("CREATE", Fonts.CREATE);
	unicodes.put("ADD_PROJECT", Fonts.ADD_PROJECT);
	unicodes.put("LAYER_MANAGEMENT", Fonts.LAYER_MANAGEMENT);
	unicodes.put("FAVORITE_ON", Fonts.FAVORITE_ON);
	unicodes.put("FAVORITE_OFF", Fonts.FAVORITE_OFF);
	unicodes.put("TRAININGSTUDIO", Fonts.TRAININGSTUDIO);
	unicodes.put("MAPSTUDIO", Fonts.MAPSTUDIO);
	unicodes.put("LABELFACTORY", Fonts.LABELFACTORY);
	unicodes.put("AISTUDIO", Fonts.AISTUDIO);
	unicodes.put("ADMIN", Fonts.ADMIN);
	unicodes.put("GRID", Fonts.GRID);
	unicodes.put("EARTH", Fonts.EARTH);
	unicodes.put("LINK", Fonts.LINK);
	unicodes.put("WRITE", Fonts.WRITE);
	unicodes.put("READ", Fonts.READ);
	unicodes.put("VISIBILITY", Fonts.VISIBILITY);
	unicodes.put("HIDDEN", Fonts.HIDDEN);
	unicodes.put("PALETTE", Fonts.PALETTE);
	unicodes.put("RETURN", Fonts.RETURN);
	unicodes.put("TERMINAL", Fonts.TERMINAL);
	unicodes.put("SHARE", Fonts.SHARE);
	unicodes.put("LOG", Fonts.LOG);
	unicodes.put("TASK", Fonts.TASK);
	unicodes.put("FEATURE", Fonts.FEATURE);
	unicodes.put("OBJECT", Fonts.OBJECT);
	unicodes.put("MODEL", Fonts.MODEL);
	unicodes.put("ROLL", Fonts.ROLL);
	unicodes.put("LAYERS", Fonts.LAYERS);
	unicodes.put("MAP_ADD", Fonts.MAP_ADD);
	unicodes.put("DELETE", Fonts.DELETE);
	unicodes.put("LOCATION", Fonts.LOCATION);
	unicodes.put("RESET", Fonts.RESET);
	unicodes.put("CATALOG_ADD", Fonts.CATALOG_ADD);
	unicodes.put("COMPARE", Fonts.COMPARE);
	unicodes.put("LEGEND", Fonts.LEGEND);
	unicodes.put("CERT", Fonts.CERT);
	unicodes.put("METADATA", Fonts.METADATA);
	unicodes.put("K8S", Fonts.K8S);
	unicodes.put("SAVE", Fonts.SAVE);
	unicodes.put("LOGO", Fonts.LOGO);
	unicodes.put("PROCESS", Fonts.PROCESS);
	unicodes.put("CANGLING_TEXT", Fonts.CANGLING_TEXT);
	unicodes.put("GEOSERVER", Fonts.GEOSERVER);
	unicodes.put("LABEL", Fonts.LABEL);
	unicodes.put("LIGHTMODE", Fonts.LIGHTMODE);
	unicodes.put("DARKMODE", Fonts.DARKMODE);
	unicodes.put("GEOTRELLIS", Fonts.GEOTRELLIS);
	unicodes.put("FOLDER_FILE", Fonts.FOLDER_FILE);
	unicodes.put("PLAY", Fonts.PLAY);
	unicodes.put("PAUSE", Fonts.PAUSE);
	unicodes.put("FILES", Fonts.FILES);
	unicodes.put("IMAGES", Fonts.IMAGES);
	unicodes.put("CLEAR_CACHE", Fonts.CLEAR_CACHE);
	unicodes.put("ALERT", Fonts.ALERT);
	unicodes.put("SFILE", Fonts.SFILE);
	unicodes.put("FOLDER", Fonts.FOLDER);
	unicodes.put("FILE", Fonts.FILE);
	unicodes.put("LEFT", Fonts.LEFT);
	unicodes.put("RIGHT", Fonts.RIGHT);
	unicodes.put("DOWN", Fonts.DOWN);
	unicodes.put("UP", Fonts.UP);
	unicodes.put("REFRESH", Fonts.REFRESH);
	unicodes.put("INFO", Fonts.INFO);
	unicodes.put("COLORS", Fonts.COLORS);
	unicodes.put("CLEAR", Fonts.CLEAR);
	unicodes.put("DONE", Fonts.DONE);
	unicodes.put("FULL_SCREEN", Fonts.FULL_SCREEN);
	unicodes.put("HARBOR", Fonts.HARBOR);
	unicodes.put("PLUS", Fonts.PLUS);
	unicodes.put("UPLOAD", Fonts.UPLOAD);
	unicodes.put("DOWNLOAD", Fonts.DOWNLOAD);
	unicodes.put("DOUBLE_LEFT", Fonts.DOUBLE_LEFT);
	unicodes.put("DOUBLE_RIGHT", Fonts.DOUBLE_RIGHT);
	unicodes.put("FINANCIAL_HARD_DISK", Fonts.FINANCIAL_HARD_DISK);
	unicodes.put("SEARCH", Fonts.SEARCH);
	unicodes.put("SETTING", Fonts.SETTING);
	unicodes.put("CONSOLE", Fonts.CONSOLE);

	}
}
