package cn.mapway.ui.client.fonts;
import java.util.HashMap;
import java.util.Map;
/**
 * Fonts
 * 图标字体常量
 * @author zhang
 */
public class Fonts {
    public static String toHtmlEntity(String fontIndex){
        if(fontIndex==null || fontIndex.length()==0){
            return "";
        }
        else{
            return "&#x"+fontIndex;
        }
    }

    	public final static String SHUAZI = "e7a7";
	public final static String JIETU = "e7a6";
	public final static String MEASURE = "e7a5";
	public final static String FENXI = "e7a4";
	public final static String HOME = "e7a3";
	public final static String JUANLIAN = "e7a1";
	public final static String DRAW = "e7a2";
	public final static String LAYER = "e603";
	public final static String LOCATION_SEARCH = "e605";
	public final static String SHANGCHUANJIEXIQUYU = "e948";
	public final static String JUXING = "e93d";
	public final static String TONGYONGBIANHUA = "e942";
	public final static String FANGWUJIANZHUQU = "e94a";
	public final static String SHUIYU = "e946";
	public final static String DUOBIANXING = "e941";
	public final static String LINDI = "e93b";
	public final static String YUANDI = "e93e";
	public final static String FAJIA = "e93a";
	public final static String DAOLUYUTIELU = "e939";
	public final static String WANGXIANG = "e932";
	public final static String QITATUDI = "e950";
	public final static String CAODI = "e94b";
	public final static String GEO_FILTER = "e7a0";
	public final static String GEOM_CORRECT = "e79f";
	public final static String SAMPLE_STA = "e79e";
	public final static String WEIXIN = "e79d";
	public final static String RENWUTUISONG = "e79c";
	public final static String IMPORTDATA = "e736";
	public final static String SPACE_TIME = "e731";
	public final static String SHELL = "e72f";
	public final static String GITIGNORE = "e798";
	public final static String PNG = "e799";
	public final static String SVG = "e79a";
	public final static String TIFF = "e79b";
	public final static String PDF = "e78c";
	public final static String SQL = "e78d";
	public final static String JSON = "e78e";
	public final static String XML = "e78f";
	public final static String YML = "e790";
	public final static String HTML = "e791";
	public final static String JAVA1 = "e792";
	public final static String MD = "e793";
	public final static String MP4 = "e794";
	public final static String XLS = "e795";
	public final static String CSS1 = "e796";
	public final static String MP3 = "e797";
	public final static String JAR = "e780";
	public final static String PY = "e781";
	public final static String FILE1 = "e782";
	public final static String EXE = "e783";
	public final static String DOCKERFILE = "e784";
	public final static String TXT = "e785";
	public final static String DOC = "e786";
	public final static String JPG = "e787";
	public final static String ISO = "e788";
	public final static String PPT = "e789";
	public final static String JS = "e78a";
	public final static String ZIP = "e78b";
	public final static String ADD_FOLDER = "e77e";
	public final static String ADD_FILE = "e77f";
	public final static String FEATURE_FILTER = "e77d";
	public final static String LANG_EN = "e77c";
	public final static String PTZ_PATROL = "e77b";
	public final static String ZOOMOUT = "e779";
	public final static String ZOOMIN = "e77a";
	public final static String MESSAGE_LIST = "e778";
	public final static String CAMERA_NIGHT = "e776";
	public final static String CAMERA_SUN = "e777";
	public final static String KV = "e775";
	public final static String NAVI_TREE = "e773";
	public final static String NAVI_BAR = "e774";
	public final static String SHANGFAN = "e771";
	public final static String XIAFAN = "e772";
	public final static String CANVAS = "e770";
	public final static String IOT_PLATFORM = "e76f";
	public final static String RBAC_ROLE_RESOURCE = "e76c";
	public final static String RBAC_RESOURCE = "e76d";
	public final static String RBAC_ROLE = "e76e";
	public final static String IOT_SERVER = "e768";
	public final static String IOT_TCP = "e769";
	public final static String IOT_MQTT = "e76a";
	public final static String IOT = "e76b";
	public final static String TIME = "e763";
	public final static String STACK_UP = "e767";
	public final static String STACK_LEFT = "e764";
	public final static String VIDEO_EVENTS = "e765";
	public final static String VIDEO_LIST = "e766";
	public final static String VIDEO_CLOUD = "e761";
	public final static String VIDEO_VIEW = "e762";
	public final static String CREATE2 = "e760";
	public final static String RUST = "e75f";
	public final static String PYTHON = "e75e";
	public final static String CSS = "e75d";
	public final static String FOLDER_SHARE = "e75b";
	public final static String FONTS = "e75c";
	public final static String MULTI_LEVEL = "e75a";
	public final static String IMAGE_BUTTON = "e759";
	public final static String NETWORK = "e758";
	public final static String THREE_SCENE = "e757";
	public final static String POPUP = "e756";
	public final static String MARKER_LIST = "e755";
	public final static String MARKER = "e754";
	public final static String PATH = "e753";
	public final static String TREE = "e750";
	public final static String LAYER_VIEW = "e751";
	public final static String LAYER_DATA = "e752";
	public final static String DISTANCE = "e74d";
	public final static String WIDTH_EQUAL = "e74e";
	public final static String HEIGHT_EQUAL = "e74f";
	public final static String RIVER = "e74c";
	public final static String YINGYANG = "e74b";
	public final static String ZHENGSANFA = "e74a";
	public final static String SHUILIANG = "e748";
	public final static String SHUIHUA = "e749";
	public final static String GANGMAO = "e740";
	public final static String TOUMINGDU = "e741";
	public final static String SHENGTAI = "e742";
	public final static String WENDU = "e743";
	public final static String YELVSU = "e744";
	public final static String ZHIBEI = "e745";
	public final static String XUANFUWU = "e746";
	public final static String HEICHOU = "e747";
	public final static String VECTOR = "e73e";
	public final static String EXPLORER = "e73f";
	public final static String CMS = "e73d";
	public final static String TABLE_STYLE = "e73c";
	public final static String JAVASCRIPT = "e73b";
	public final static String PIN = "e73a";
	public final static String BOLD = "e737";
	public final static String UNDERLINE = "e738";
	public final static String ITALIC = "e739";
	public final static String IFRAME = "e735";
	public final static String MAP_GLOBAL = "e733";
	public final static String DATA_SOURCE = "e734";
	public final static String TABLEDATA = "e732";
	public final static String TRAIN = "e72c";
	public final static String REST = "e72d";
	public final static String CSV = "e72e";
	public final static String LOGFILE = "e730";
	public final static String CURSOR = "e72b";
	public final static String CHART = "e72a";
	public final static String LAB = "e729";
	public final static String LAKE2 = "e728";
	public final static String EMPTY = "e727";
	public final static String PYRAMID = "e726";
	public final static String UNLOCK = "e724";
	public final static String LOCK = "e725";
	public final static String DAOHANG_YIWEN = "e8ab";
	public final static String DAOHANG_SHEZHI = "e8ac";
	public final static String A_ZHONGZHISHUAXIN = "e8ad";
	public final static String TIANJIA = "e8ae";
	public final static String SOUSUO1 = "e8af";
	public final static String GONGNENGZHUANGSHI = "e8b0";
	public final static String YULAN2 = "e8b1";
	public final static String A_YANGBENMOXING = "e8b2";
	public final static String BIANJI = "e8b3";
	public final static String BOFANG2 = "e8b4";
	public final static String A_YULANYANJING = "e8b5";
	public final static String FANHUI = "e8b6";
	public final static String SHANGYI = "e8b7";
	public final static String DAOHANG_SHEZHI1 = "e8b8";
	public final static String DUOXUAN = "e8ba";
	public final static String A_YINCANGSANDIAN = "e8bb";
	public final static String SHEZHI = "e8bc";
	public final static String GONGNENGMOXING = "e8bd";
	public final static String SHUAXIN = "e8c1";
	public final static String SHANCHU = "e8c2";
	public final static String DIAN = "e8c3";
	public final static String JIANYAN = "e8c4";
	public final static String A_SHOUCANGWEIXUANZHONG = "e8c5";
	public final static String BIAOZHU = "e8c6";
	public final static String A_SHOUCANGXUANZHONG = "e8c7";
	public final static String CHECK = "e71f";
	public final static String FINISH = "e720";
	public final static String ERROR1 = "e721";
	public final static String PAUSE1 = "e722";
	public final static String WAIT = "e723";
	public final static String PEN = "e71e";
	public final static String P_OUT = "e71b";
	public final static String P_INPUT = "e71c";
	public final static String P_RUNNING = "e71d";
	public final static String BORDER = "e718";
	public final static String SLIDER = "e719";
	public final static String LAYOUT1 = "e71a";
	public final static String DROPDOWN = "e717";
	public final static String ATTRIBUTE = "e716";
	public final static String PILIANGTIANJIA = "e715";
	public final static String JIAZAIZHONG = "e714";
	public final static String THUNDER = "e713";
	public final static String EVENTS = "e712";
	public final static String CLOUD_CONTROL = "e711";
	public final static String RECT = "e710";
	public final static String TOWER = "e70f";
	public final static String FLAG = "e709";
	public final static String VIDEO = "e707";
	public final static String QIYE = "e708";
	public final static String EXIT = "e706";
	public final static String PREVIEW = "e705";
	public final static String GRID_MEDIUM1 = "e70a";
	public final static String PHOTO1 = "e70b";
	public final static String TH_LARGE1 = "e70c";
	public final static String TH1 = "e70d";
	public final static String TH_LIST1 = "e70e";
	public final static String JAVA = "e700";
	public final static String KAFKA = "e701";
	public final static String API = "e702";
	public final static String UNKNOWN1 = "e703";
	public final static String DOCKER = "e704";
	public final static String ICON_CD = "e6e9";
	public final static String ICON_CK = "e6ec";
	public final static String ICON_DC = "e6ee";
	public final static String ICON_JZWDM = "e6ef";
	public final static String ICON_GD = "e6f0";
	public final static String ICON_JZWCM = "e6f1";
	public final static String ICON_LTTYC = "e6f2";
	public final static String ICON_GZLTJ = "e6f3";
	public final static String ICON_QTSGSS = "e6f4";
	public final static String ICON_SJCP = "e6f5";
	public final static String ICON_QTYHDB = "e6f6";
	public final static String ICON_GHC = "e6f7";
	public final static String ICON_JTSS = "e6f8";
	public final static String ICON_WDFX = "e6f9";
	public final static String ICON_TZJSCS = "e6fa";
	public final static String ICON_LD = "e6fb";
	public final static String ICON_GLRY = "e6fc";
	public final static String ICON_DB = "e6fd";
	public final static String ICON_WSDP = "e6fe";
	public final static String ICON_YD = "e6ff";
	public final static String ICON_XS1 = "e6e8";
	public final static String ICON_XZMX = "e6eb";
	public final static String ICON_YC = "e6e1";
	public final static String ICON_PODXX = "e6e5";
	public final static String ICON_BCRW = "e6e2";
	public final static String ICON_SJ = "e6e3";
	public final static String ICON_RZ = "e6e4";
	public final static String ICON_TCDW = "e6e6";
	public final static String ICON_JGCK = "e6e7";
	public final static String ICON_XZYX = "e6ea";
	public final static String GITLAB = "f1b7";
	public final static String ICON_LX = "e6d9";
	public final static String ICON_SC1 = "e6df";
	public final static String ICON_MB = "e6e0";
	public final static String ICON_JQ = "e6de";
	public final static String ICON_SCTS = "e6dd";
	public final static String ICON_BJ = "e6d8";
	public final static String ICON_TXFGMX = "e6da";
	public final static String ICON_FB = "e6db";
	public final static String ICON_SHJSJ = "e6dc";
	public final static String ICON_TJ1 = "e6d7";
	public final static String ICON_RQ = "e6d6";
	public final static String ICON_XX = "e8c0";
	public final static String ICON_XL = "e62d";
	public final static String ICON_FHDDHY = "e6ca";
	public final static String ICON_FH = "e6cb";
	public final static String ICON_BF = "e6cc";
	public final static String ICON_LB = "e6cd";
	public final static String ICON_SC = "e6ce";
	public final static String ICON_KP = "e6cf";
	public final static String ICON_SS = "e6d0";
	public final static String ICON_SX = "e6d1";
	public final static String ICON_SX1 = "e6d2";
	public final static String ICON_TJ = "e6d3";
	public final static String ICON_ZD = "e6d4";
	public final static String ICON_SZ = "e6d5";
	public final static String FUZHI = "e6c7";
	public final static String NIANTIE = "e6c9";
	public final static String RABBITMQ_LOGO_SVGREPO_COM = "e6c5";
	public final static String PROJECT = "e6c4";
	public final static String ZHUANHUAN = "e6c8";
	public final static String XUANZE = "e61c";
	public final static String CAMERA = "e6c6";
	public final static String SEARCHABLE = "e6c3";
	public final static String ALERT1 = "e6c1";
	public final static String TABLE = "e6c2";
	public final static String SERIAL = "e6c0";
	public final static String INT8 = "e6bf";
	public final static String UNKNOWN = "e6be";
	public final static String GEO_COLLECTION = "e6bd";
	public final static String LINE = "e6b7";
	public final static String POINT = "e6b8";
	public final static String POLYGON = "e6b9";
	public final static String LINES = "e6ba";
	public final static String POINTS = "e6bb";
	public final static String POLYGONS = "e6bc";
	public final static String POSTGIS = "e6b6";
	public final static String CATEGORY_PLUS = "e6b5";
	public final static String SHIELD_INFO = "e6b4";
	public final static String CATALOG = "e6b3";
	public final static String MOVE = "e6b2";
	public final static String WORKSPACE = "e66e";
	public final static String MULTI_SELECT = "e6b1";
	public final static String RENAME = "e6af";
	public final static String SELECTED = "e6b0";
	public final static String APPS = "e6ae";
	public final static String UPLOAD_BIG = "e6ac";
	public final static String UPLOAD_SMALL = "e6ad";
	public final static String ACCOUNT = "e6ab";
	public final static String IMAGE = "e6a9";
	public final static String SHAPES = "e6aa";
	public final static String MAP_BORDER = "e6a8";
	public final static String PIN_FILL = "e6a7";
	public final static String RS = "e6a6";
	public final static String TIP = "e6a5";
	public final static String ERROR = "e6a4";
	public final static String PREPARE = "e6a3";
	public final static String MAP_CONFIG = "e6a1";
	public final static String UI_CONFIG = "e6a2";
	public final static String IB = "e6a0";
	public final static String IMAGEBOT = "e69f";
	public final static String SHUTDOWN = "e69e";
	public final static String THIRD_PARTY = "e69d";
	public final static String STATISTIC = "e69c";
	public final static String SORT_ASCENDING = "e699";
	public final static String SORT_VARIANT = "e69a";
	public final static String SORT_DESCENDING = "e69b";
	public final static String MAP_SEARCH = "e698";
	public final static String QUEUE = "e697";
	public final static String PAUSEING = "e689";
	public final static String RUNNING = "e68a";
	public final static String STOP = "e695";
	public final static String STOPPING = "e696";
	public final static String NUMBER = "e685";
	public final static String TEXTFORMAT_123 = "e692";
	public final static String CALENDAR = "e693";
	public final static String ABC = "e694";
	public final static String KEY = "e683";
	public final static String CLOSE_L = "e684";
	public final static String CONTROLER = "e686";
	public final static String FIRE = "e687";
	public final static String MOVABLE = "e688";
	public final static String MORE = "e68b";
	public final static String SORT1 = "e68c";
	public final static String DESIGN = "e68d";
	public final static String ON = "e68e";
	public final static String CLOSE1 = "e68f";
	public final static String REMOVE = "e690";
	public final static String OFF = "e691";
	public final static String ZHONG = "e682";
	public final static String OPEN = "e681";
	public final static String DEVELOPER = "e680";
	public final static String SCHEMA_PROPERTY = "e67f";
	public final static String WARNING = "e67e";
	public final static String STYLE = "e67d";
	public final static String OVERVIEW = "e67c";
	public final static String PRODUCT = "e66c";
	public final static String LAND = "e672";
	public final static String CHEMETRY = "e673";
	public final static String RESIDENT = "e674";
	public final static String ROAD = "e675";
	public final static String FIRE_ENERGY = "e676";
	public final static String DAPENG = "e677";
	public final static String TANK = "e678";
	public final static String WEI_MINER = "e679";
	public final static String WATER_ENERGY = "e67a";
	public final static String WATER_FARM = "e67b";
	public final static String FE = "e670";
	public final static String BUILDING = "e671";
	public final static String EME_TEXT = "e66f";
	public final static String LABEL_MAKER = "e66d";
	public final static String CONTRAST = "e66b";
	public final static String MODULE = "e66a";
	public final static String ALIGN_VERTICAL = "e668";
	public final static String ALIGN_HORIZONTAL = "e669";
	public final static String ALIGN_BOTTOM = "e660";
	public final static String ALIGN_LEFT = "e661";
	public final static String ALIGN_CENTER = "e662";
	public final static String ALIGN_RIGHT = "e663";
	public final static String TEXT_WRAP = "e664";
	public final static String ALIGN_MIDDLE = "e665";
	public final static String LIST = "e666";
	public final static String ALIGN_TOP = "e667";
	public final static String HELP = "e65f";
	public final static String APPLICATION = "e65e";
	public final static String IMAGESTUDIO = "e65d";
	public final static String PLOTTING = "e65c";
	public final static String SCHEMA = "e656";
	public final static String FLOW = "e65b";
	public final static String CLEAN_SAMPLE = "e65a";
	public final static String SAMPLE_PRODUCT = "e659";
	public final static String SAMPLE_PLOTTING = "e658";
	public final static String IMPORT_SAMPLE = "e657";
	public final static String TOOLBOX = "e64f";
	public final static String HYPERFRACTIONATION = "e655";
	public final static String ENHANCE_COLOR = "e654";
	public final static String CLOUD_DETECTION = "e653";
	public final static String ORTHOPHOTO = "e652";
	public final static String LAYOUT = "e650";
	public final static String CREATE = "e651";
	public final static String ADD_PROJECT = "e64e";
	public final static String LAYER_MANAGEMENT = "e64d";
	public final static String FAVORITE_ON = "e64c";
	public final static String FAVORITE_OFF = "e64b";
	public final static String TRAININGSTUDIO = "e64a";
	public final static String MAPSTUDIO = "e649";
	public final static String LABELFACTORY = "e606";
	public final static String AISTUDIO = "e600";
	public final static String ADMIN = "e6ed";
	public final static String GRID = "e648";
	public final static String EARTH = "e647";
	public final static String LINK = "e646";
	public final static String WRITE = "e645";
	public final static String READ = "e644";
	public final static String VISIBILITY = "e639";
	public final static String HIDDEN = "e63a";
	public final static String PALETTE = "e643";
	public final static String RETURN = "e63f";
	public final static String TERMINAL = "e640";
	public final static String SHARE = "e641";
	public final static String LOG = "e642";
	public final static String TASK = "e63b";
	public final static String FEATURE = "e63c";
	public final static String OBJECT = "e63d";
	public final static String MODEL = "e63e";
	public final static String ROLL = "e631";
	public final static String LAYERS = "e632";
	public final static String MAP_ADD = "e633";
	public final static String DELETE = "e634";
	public final static String LOCATION = "e635";
	public final static String RESET = "e636";
	public final static String CATALOG_ADD = "e637";
	public final static String COMPARE = "e638";
	public final static String LEGEND = "e630";
	public final static String CERT = "e62c";
	public final static String METADATA = "e62e";
	public final static String K8S = "e62f";
	public final static String SAVE = "e62b";
	public final static String LOGO = "e62a";
	public final static String PROCESS = "e628";
	public final static String CANGLING_TEXT = "e629";
	public final static String GEOSERVER = "e626";
	public final static String LABEL = "e627";
	public final static String LIGHTMODE = "e624";
	public final static String DARKMODE = "e625";
	public final static String GEOTRELLIS = "e623";
	public final static String FOLDER_FILE = "e622";
	public final static String PLAY = "e620";
	public final static String PAUSE = "e621";
	public final static String FILES = "e61f";
	public final static String IMAGES = "e61e";
	public final static String CLEAR_CACHE = "e61d";
	public final static String ALERT = "e61b";
	public final static String SFILE = "e61a";
	public final static String FOLDER = "e618";
	public final static String FILE = "e619";
	public final static String LEFT = "e616";
	public final static String RIGHT = "e617";
	public final static String DOWN = "e614";
	public final static String UP = "e615";
	public final static String REFRESH = "e613";
	public final static String INFO = "e610";
	public final static String COLORS = "e611";
	public final static String CLEAR = "e612";
	public final static String DONE = "e60f";
	public final static String FULL_SCREEN = "e60c";
	public final static String HARBOR = "e60d";
	public final static String PLUS = "e60e";
	public final static String UPLOAD = "e60a";
	public final static String DOWNLOAD = "e60b";
	public final static String DOUBLE_LEFT = "e608";
	public final static String DOUBLE_RIGHT = "e609";
	public final static String FINANCIAL_HARD_DISK = "e607";
	public final static String SEARCH = "e604";
	public final static String SETTING = "e602";
	public final static String CONSOLE = "e601";

   public static Map<String,String> unicodes;
	static {
		unicodes=new HashMap<>();
		//unicodes.put("console", Fonts.CONSOLE);
			unicodes.put("SHUAZI", Fonts.SHUAZI);
	unicodes.put("JIETU", Fonts.JIETU);
	unicodes.put("MEASURE", Fonts.MEASURE);
	unicodes.put("FENXI", Fonts.FENXI);
	unicodes.put("HOME", Fonts.HOME);
	unicodes.put("JUANLIAN", Fonts.JUANLIAN);
	unicodes.put("DRAW", Fonts.DRAW);
	unicodes.put("LAYER", Fonts.LAYER);
	unicodes.put("LOCATION_SEARCH", Fonts.LOCATION_SEARCH);
	unicodes.put("SHANGCHUANJIEXIQUYU", Fonts.SHANGCHUANJIEXIQUYU);
	unicodes.put("JUXING", Fonts.JUXING);
	unicodes.put("TONGYONGBIANHUA", Fonts.TONGYONGBIANHUA);
	unicodes.put("FANGWUJIANZHUQU", Fonts.FANGWUJIANZHUQU);
	unicodes.put("SHUIYU", Fonts.SHUIYU);
	unicodes.put("DUOBIANXING", Fonts.DUOBIANXING);
	unicodes.put("LINDI", Fonts.LINDI);
	unicodes.put("YUANDI", Fonts.YUANDI);
	unicodes.put("FAJIA", Fonts.FAJIA);
	unicodes.put("DAOLUYUTIELU", Fonts.DAOLUYUTIELU);
	unicodes.put("WANGXIANG", Fonts.WANGXIANG);
	unicodes.put("QITATUDI", Fonts.QITATUDI);
	unicodes.put("CAODI", Fonts.CAODI);
	unicodes.put("GEO_FILTER", Fonts.GEO_FILTER);
	unicodes.put("GEOM_CORRECT", Fonts.GEOM_CORRECT);
	unicodes.put("SAMPLE_STA", Fonts.SAMPLE_STA);
	unicodes.put("WEIXIN", Fonts.WEIXIN);
	unicodes.put("RENWUTUISONG", Fonts.RENWUTUISONG);
	unicodes.put("IMPORTDATA", Fonts.IMPORTDATA);
	unicodes.put("SPACE_TIME", Fonts.SPACE_TIME);
	unicodes.put("SHELL", Fonts.SHELL);
	unicodes.put("GITIGNORE", Fonts.GITIGNORE);
	unicodes.put("PNG", Fonts.PNG);
	unicodes.put("SVG", Fonts.SVG);
	unicodes.put("TIFF", Fonts.TIFF);
	unicodes.put("PDF", Fonts.PDF);
	unicodes.put("SQL", Fonts.SQL);
	unicodes.put("JSON", Fonts.JSON);
	unicodes.put("XML", Fonts.XML);
	unicodes.put("YML", Fonts.YML);
	unicodes.put("HTML", Fonts.HTML);
	unicodes.put("JAVA1", Fonts.JAVA1);
	unicodes.put("MD", Fonts.MD);
	unicodes.put("MP4", Fonts.MP4);
	unicodes.put("XLS", Fonts.XLS);
	unicodes.put("CSS1", Fonts.CSS1);
	unicodes.put("MP3", Fonts.MP3);
	unicodes.put("JAR", Fonts.JAR);
	unicodes.put("PY", Fonts.PY);
	unicodes.put("FILE1", Fonts.FILE1);
	unicodes.put("EXE", Fonts.EXE);
	unicodes.put("DOCKERFILE", Fonts.DOCKERFILE);
	unicodes.put("TXT", Fonts.TXT);
	unicodes.put("DOC", Fonts.DOC);
	unicodes.put("JPG", Fonts.JPG);
	unicodes.put("ISO", Fonts.ISO);
	unicodes.put("PPT", Fonts.PPT);
	unicodes.put("JS", Fonts.JS);
	unicodes.put("ZIP", Fonts.ZIP);
	unicodes.put("ADD_FOLDER", Fonts.ADD_FOLDER);
	unicodes.put("ADD_FILE", Fonts.ADD_FILE);
	unicodes.put("FEATURE_FILTER", Fonts.FEATURE_FILTER);
	unicodes.put("LANG_EN", Fonts.LANG_EN);
	unicodes.put("PTZ_PATROL", Fonts.PTZ_PATROL);
	unicodes.put("ZOOMOUT", Fonts.ZOOMOUT);
	unicodes.put("ZOOMIN", Fonts.ZOOMIN);
	unicodes.put("MESSAGE_LIST", Fonts.MESSAGE_LIST);
	unicodes.put("CAMERA_NIGHT", Fonts.CAMERA_NIGHT);
	unicodes.put("CAMERA_SUN", Fonts.CAMERA_SUN);
	unicodes.put("KV", Fonts.KV);
	unicodes.put("NAVI_TREE", Fonts.NAVI_TREE);
	unicodes.put("NAVI_BAR", Fonts.NAVI_BAR);
	unicodes.put("SHANGFAN", Fonts.SHANGFAN);
	unicodes.put("XIAFAN", Fonts.XIAFAN);
	unicodes.put("CANVAS", Fonts.CANVAS);
	unicodes.put("IOT_PLATFORM", Fonts.IOT_PLATFORM);
	unicodes.put("RBAC_ROLE_RESOURCE", Fonts.RBAC_ROLE_RESOURCE);
	unicodes.put("RBAC_RESOURCE", Fonts.RBAC_RESOURCE);
	unicodes.put("RBAC_ROLE", Fonts.RBAC_ROLE);
	unicodes.put("IOT_SERVER", Fonts.IOT_SERVER);
	unicodes.put("IOT_TCP", Fonts.IOT_TCP);
	unicodes.put("IOT_MQTT", Fonts.IOT_MQTT);
	unicodes.put("IOT", Fonts.IOT);
	unicodes.put("TIME", Fonts.TIME);
	unicodes.put("STACK_UP", Fonts.STACK_UP);
	unicodes.put("STACK_LEFT", Fonts.STACK_LEFT);
	unicodes.put("VIDEO_EVENTS", Fonts.VIDEO_EVENTS);
	unicodes.put("VIDEO_LIST", Fonts.VIDEO_LIST);
	unicodes.put("VIDEO_CLOUD", Fonts.VIDEO_CLOUD);
	unicodes.put("VIDEO_VIEW", Fonts.VIDEO_VIEW);
	unicodes.put("CREATE2", Fonts.CREATE2);
	unicodes.put("RUST", Fonts.RUST);
	unicodes.put("PYTHON", Fonts.PYTHON);
	unicodes.put("CSS", Fonts.CSS);
	unicodes.put("FOLDER_SHARE", Fonts.FOLDER_SHARE);
	unicodes.put("FONTS", Fonts.FONTS);
	unicodes.put("MULTI_LEVEL", Fonts.MULTI_LEVEL);
	unicodes.put("IMAGE_BUTTON", Fonts.IMAGE_BUTTON);
	unicodes.put("NETWORK", Fonts.NETWORK);
	unicodes.put("THREE_SCENE", Fonts.THREE_SCENE);
	unicodes.put("POPUP", Fonts.POPUP);
	unicodes.put("MARKER_LIST", Fonts.MARKER_LIST);
	unicodes.put("MARKER", Fonts.MARKER);
	unicodes.put("PATH", Fonts.PATH);
	unicodes.put("TREE", Fonts.TREE);
	unicodes.put("LAYER_VIEW", Fonts.LAYER_VIEW);
	unicodes.put("LAYER_DATA", Fonts.LAYER_DATA);
	unicodes.put("DISTANCE", Fonts.DISTANCE);
	unicodes.put("WIDTH_EQUAL", Fonts.WIDTH_EQUAL);
	unicodes.put("HEIGHT_EQUAL", Fonts.HEIGHT_EQUAL);
	unicodes.put("RIVER", Fonts.RIVER);
	unicodes.put("YINGYANG", Fonts.YINGYANG);
	unicodes.put("ZHENGSANFA", Fonts.ZHENGSANFA);
	unicodes.put("SHUILIANG", Fonts.SHUILIANG);
	unicodes.put("SHUIHUA", Fonts.SHUIHUA);
	unicodes.put("GANGMAO", Fonts.GANGMAO);
	unicodes.put("TOUMINGDU", Fonts.TOUMINGDU);
	unicodes.put("SHENGTAI", Fonts.SHENGTAI);
	unicodes.put("WENDU", Fonts.WENDU);
	unicodes.put("YELVSU", Fonts.YELVSU);
	unicodes.put("ZHIBEI", Fonts.ZHIBEI);
	unicodes.put("XUANFUWU", Fonts.XUANFUWU);
	unicodes.put("HEICHOU", Fonts.HEICHOU);
	unicodes.put("VECTOR", Fonts.VECTOR);
	unicodes.put("EXPLORER", Fonts.EXPLORER);
	unicodes.put("CMS", Fonts.CMS);
	unicodes.put("TABLE_STYLE", Fonts.TABLE_STYLE);
	unicodes.put("JAVASCRIPT", Fonts.JAVASCRIPT);
	unicodes.put("PIN", Fonts.PIN);
	unicodes.put("BOLD", Fonts.BOLD);
	unicodes.put("UNDERLINE", Fonts.UNDERLINE);
	unicodes.put("ITALIC", Fonts.ITALIC);
	unicodes.put("IFRAME", Fonts.IFRAME);
	unicodes.put("MAP_GLOBAL", Fonts.MAP_GLOBAL);
	unicodes.put("DATA_SOURCE", Fonts.DATA_SOURCE);
	unicodes.put("TABLEDATA", Fonts.TABLEDATA);
	unicodes.put("TRAIN", Fonts.TRAIN);
	unicodes.put("REST", Fonts.REST);
	unicodes.put("CSV", Fonts.CSV);
	unicodes.put("LOGFILE", Fonts.LOGFILE);
	unicodes.put("CURSOR", Fonts.CURSOR);
	unicodes.put("CHART", Fonts.CHART);
	unicodes.put("LAB", Fonts.LAB);
	unicodes.put("LAKE2", Fonts.LAKE2);
	unicodes.put("EMPTY", Fonts.EMPTY);
	unicodes.put("PYRAMID", Fonts.PYRAMID);
	unicodes.put("UNLOCK", Fonts.UNLOCK);
	unicodes.put("LOCK", Fonts.LOCK);
	unicodes.put("DAOHANG_YIWEN", Fonts.DAOHANG_YIWEN);
	unicodes.put("DAOHANG_SHEZHI", Fonts.DAOHANG_SHEZHI);
	unicodes.put("A_ZHONGZHISHUAXIN", Fonts.A_ZHONGZHISHUAXIN);
	unicodes.put("TIANJIA", Fonts.TIANJIA);
	unicodes.put("SOUSUO1", Fonts.SOUSUO1);
	unicodes.put("GONGNENGZHUANGSHI", Fonts.GONGNENGZHUANGSHI);
	unicodes.put("YULAN2", Fonts.YULAN2);
	unicodes.put("A_YANGBENMOXING", Fonts.A_YANGBENMOXING);
	unicodes.put("BIANJI", Fonts.BIANJI);
	unicodes.put("BOFANG2", Fonts.BOFANG2);
	unicodes.put("A_YULANYANJING", Fonts.A_YULANYANJING);
	unicodes.put("FANHUI", Fonts.FANHUI);
	unicodes.put("SHANGYI", Fonts.SHANGYI);
	unicodes.put("DAOHANG_SHEZHI1", Fonts.DAOHANG_SHEZHI1);
	unicodes.put("DUOXUAN", Fonts.DUOXUAN);
	unicodes.put("A_YINCANGSANDIAN", Fonts.A_YINCANGSANDIAN);
	unicodes.put("SHEZHI", Fonts.SHEZHI);
	unicodes.put("GONGNENGMOXING", Fonts.GONGNENGMOXING);
	unicodes.put("SHUAXIN", Fonts.SHUAXIN);
	unicodes.put("SHANCHU", Fonts.SHANCHU);
	unicodes.put("DIAN", Fonts.DIAN);
	unicodes.put("JIANYAN", Fonts.JIANYAN);
	unicodes.put("A_SHOUCANGWEIXUANZHONG", Fonts.A_SHOUCANGWEIXUANZHONG);
	unicodes.put("BIAOZHU", Fonts.BIAOZHU);
	unicodes.put("A_SHOUCANGXUANZHONG", Fonts.A_SHOUCANGXUANZHONG);
	unicodes.put("CHECK", Fonts.CHECK);
	unicodes.put("FINISH", Fonts.FINISH);
	unicodes.put("ERROR1", Fonts.ERROR1);
	unicodes.put("PAUSE1", Fonts.PAUSE1);
	unicodes.put("WAIT", Fonts.WAIT);
	unicodes.put("PEN", Fonts.PEN);
	unicodes.put("P_OUT", Fonts.P_OUT);
	unicodes.put("P_INPUT", Fonts.P_INPUT);
	unicodes.put("P_RUNNING", Fonts.P_RUNNING);
	unicodes.put("BORDER", Fonts.BORDER);
	unicodes.put("SLIDER", Fonts.SLIDER);
	unicodes.put("LAYOUT1", Fonts.LAYOUT1);
	unicodes.put("DROPDOWN", Fonts.DROPDOWN);
	unicodes.put("ATTRIBUTE", Fonts.ATTRIBUTE);
	unicodes.put("PILIANGTIANJIA", Fonts.PILIANGTIANJIA);
	unicodes.put("JIAZAIZHONG", Fonts.JIAZAIZHONG);
	unicodes.put("THUNDER", Fonts.THUNDER);
	unicodes.put("EVENTS", Fonts.EVENTS);
	unicodes.put("CLOUD_CONTROL", Fonts.CLOUD_CONTROL);
	unicodes.put("RECT", Fonts.RECT);
	unicodes.put("TOWER", Fonts.TOWER);
	unicodes.put("FLAG", Fonts.FLAG);
	unicodes.put("VIDEO", Fonts.VIDEO);
	unicodes.put("QIYE", Fonts.QIYE);
	unicodes.put("EXIT", Fonts.EXIT);
	unicodes.put("PREVIEW", Fonts.PREVIEW);
	unicodes.put("GRID_MEDIUM1", Fonts.GRID_MEDIUM1);
	unicodes.put("PHOTO1", Fonts.PHOTO1);
	unicodes.put("TH_LARGE1", Fonts.TH_LARGE1);
	unicodes.put("TH1", Fonts.TH1);
	unicodes.put("TH_LIST1", Fonts.TH_LIST1);
	unicodes.put("JAVA", Fonts.JAVA);
	unicodes.put("KAFKA", Fonts.KAFKA);
	unicodes.put("API", Fonts.API);
	unicodes.put("UNKNOWN1", Fonts.UNKNOWN1);
	unicodes.put("DOCKER", Fonts.DOCKER);
	unicodes.put("ICON_CD", Fonts.ICON_CD);
	unicodes.put("ICON_CK", Fonts.ICON_CK);
	unicodes.put("ICON_DC", Fonts.ICON_DC);
	unicodes.put("ICON_JZWDM", Fonts.ICON_JZWDM);
	unicodes.put("ICON_GD", Fonts.ICON_GD);
	unicodes.put("ICON_JZWCM", Fonts.ICON_JZWCM);
	unicodes.put("ICON_LTTYC", Fonts.ICON_LTTYC);
	unicodes.put("ICON_GZLTJ", Fonts.ICON_GZLTJ);
	unicodes.put("ICON_QTSGSS", Fonts.ICON_QTSGSS);
	unicodes.put("ICON_SJCP", Fonts.ICON_SJCP);
	unicodes.put("ICON_QTYHDB", Fonts.ICON_QTYHDB);
	unicodes.put("ICON_GHC", Fonts.ICON_GHC);
	unicodes.put("ICON_JTSS", Fonts.ICON_JTSS);
	unicodes.put("ICON_WDFX", Fonts.ICON_WDFX);
	unicodes.put("ICON_TZJSCS", Fonts.ICON_TZJSCS);
	unicodes.put("ICON_LD", Fonts.ICON_LD);
	unicodes.put("ICON_GLRY", Fonts.ICON_GLRY);
	unicodes.put("ICON_DB", Fonts.ICON_DB);
	unicodes.put("ICON_WSDP", Fonts.ICON_WSDP);
	unicodes.put("ICON_YD", Fonts.ICON_YD);
	unicodes.put("ICON_XS1", Fonts.ICON_XS1);
	unicodes.put("ICON_XZMX", Fonts.ICON_XZMX);
	unicodes.put("ICON_YC", Fonts.ICON_YC);
	unicodes.put("ICON_PODXX", Fonts.ICON_PODXX);
	unicodes.put("ICON_BCRW", Fonts.ICON_BCRW);
	unicodes.put("ICON_SJ", Fonts.ICON_SJ);
	unicodes.put("ICON_RZ", Fonts.ICON_RZ);
	unicodes.put("ICON_TCDW", Fonts.ICON_TCDW);
	unicodes.put("ICON_JGCK", Fonts.ICON_JGCK);
	unicodes.put("ICON_XZYX", Fonts.ICON_XZYX);
	unicodes.put("GITLAB", Fonts.GITLAB);
	unicodes.put("ICON_LX", Fonts.ICON_LX);
	unicodes.put("ICON_SC1", Fonts.ICON_SC1);
	unicodes.put("ICON_MB", Fonts.ICON_MB);
	unicodes.put("ICON_JQ", Fonts.ICON_JQ);
	unicodes.put("ICON_SCTS", Fonts.ICON_SCTS);
	unicodes.put("ICON_BJ", Fonts.ICON_BJ);
	unicodes.put("ICON_TXFGMX", Fonts.ICON_TXFGMX);
	unicodes.put("ICON_FB", Fonts.ICON_FB);
	unicodes.put("ICON_SHJSJ", Fonts.ICON_SHJSJ);
	unicodes.put("ICON_TJ1", Fonts.ICON_TJ1);
	unicodes.put("ICON_RQ", Fonts.ICON_RQ);
	unicodes.put("ICON_XX", Fonts.ICON_XX);
	unicodes.put("ICON_XL", Fonts.ICON_XL);
	unicodes.put("ICON_FHDDHY", Fonts.ICON_FHDDHY);
	unicodes.put("ICON_FH", Fonts.ICON_FH);
	unicodes.put("ICON_BF", Fonts.ICON_BF);
	unicodes.put("ICON_LB", Fonts.ICON_LB);
	unicodes.put("ICON_SC", Fonts.ICON_SC);
	unicodes.put("ICON_KP", Fonts.ICON_KP);
	unicodes.put("ICON_SS", Fonts.ICON_SS);
	unicodes.put("ICON_SX", Fonts.ICON_SX);
	unicodes.put("ICON_SX1", Fonts.ICON_SX1);
	unicodes.put("ICON_TJ", Fonts.ICON_TJ);
	unicodes.put("ICON_ZD", Fonts.ICON_ZD);
	unicodes.put("ICON_SZ", Fonts.ICON_SZ);
	unicodes.put("FUZHI", Fonts.FUZHI);
	unicodes.put("NIANTIE", Fonts.NIANTIE);
	unicodes.put("RABBITMQ_LOGO_SVGREPO_COM", Fonts.RABBITMQ_LOGO_SVGREPO_COM);
	unicodes.put("PROJECT", Fonts.PROJECT);
	unicodes.put("ZHUANHUAN", Fonts.ZHUANHUAN);
	unicodes.put("XUANZE", Fonts.XUANZE);
	unicodes.put("CAMERA", Fonts.CAMERA);
	unicodes.put("SEARCHABLE", Fonts.SEARCHABLE);
	unicodes.put("ALERT1", Fonts.ALERT1);
	unicodes.put("TABLE", Fonts.TABLE);
	unicodes.put("SERIAL", Fonts.SERIAL);
	unicodes.put("INT8", Fonts.INT8);
	unicodes.put("UNKNOWN", Fonts.UNKNOWN);
	unicodes.put("GEO_COLLECTION", Fonts.GEO_COLLECTION);
	unicodes.put("LINE", Fonts.LINE);
	unicodes.put("POINT", Fonts.POINT);
	unicodes.put("POLYGON", Fonts.POLYGON);
	unicodes.put("LINES", Fonts.LINES);
	unicodes.put("POINTS", Fonts.POINTS);
	unicodes.put("POLYGONS", Fonts.POLYGONS);
	unicodes.put("POSTGIS", Fonts.POSTGIS);
	unicodes.put("CATEGORY_PLUS", Fonts.CATEGORY_PLUS);
	unicodes.put("SHIELD_INFO", Fonts.SHIELD_INFO);
	unicodes.put("CATALOG", Fonts.CATALOG);
	unicodes.put("MOVE", Fonts.MOVE);
	unicodes.put("WORKSPACE", Fonts.WORKSPACE);
	unicodes.put("MULTI_SELECT", Fonts.MULTI_SELECT);
	unicodes.put("RENAME", Fonts.RENAME);
	unicodes.put("SELECTED", Fonts.SELECTED);
	unicodes.put("APPS", Fonts.APPS);
	unicodes.put("UPLOAD_BIG", Fonts.UPLOAD_BIG);
	unicodes.put("UPLOAD_SMALL", Fonts.UPLOAD_SMALL);
	unicodes.put("ACCOUNT", Fonts.ACCOUNT);
	unicodes.put("IMAGE", Fonts.IMAGE);
	unicodes.put("SHAPES", Fonts.SHAPES);
	unicodes.put("MAP_BORDER", Fonts.MAP_BORDER);
	unicodes.put("PIN_FILL", Fonts.PIN_FILL);
	unicodes.put("RS", Fonts.RS);
	unicodes.put("TIP", Fonts.TIP);
	unicodes.put("ERROR", Fonts.ERROR);
	unicodes.put("PREPARE", Fonts.PREPARE);
	unicodes.put("MAP_CONFIG", Fonts.MAP_CONFIG);
	unicodes.put("UI_CONFIG", Fonts.UI_CONFIG);
	unicodes.put("IB", Fonts.IB);
	unicodes.put("IMAGEBOT", Fonts.IMAGEBOT);
	unicodes.put("SHUTDOWN", Fonts.SHUTDOWN);
	unicodes.put("THIRD_PARTY", Fonts.THIRD_PARTY);
	unicodes.put("STATISTIC", Fonts.STATISTIC);
	unicodes.put("SORT_ASCENDING", Fonts.SORT_ASCENDING);
	unicodes.put("SORT_VARIANT", Fonts.SORT_VARIANT);
	unicodes.put("SORT_DESCENDING", Fonts.SORT_DESCENDING);
	unicodes.put("MAP_SEARCH", Fonts.MAP_SEARCH);
	unicodes.put("QUEUE", Fonts.QUEUE);
	unicodes.put("PAUSEING", Fonts.PAUSEING);
	unicodes.put("RUNNING", Fonts.RUNNING);
	unicodes.put("STOP", Fonts.STOP);
	unicodes.put("STOPPING", Fonts.STOPPING);
	unicodes.put("NUMBER", Fonts.NUMBER);
	unicodes.put("TEXTFORMAT_123", Fonts.TEXTFORMAT_123);
	unicodes.put("CALENDAR", Fonts.CALENDAR);
	unicodes.put("ABC", Fonts.ABC);
	unicodes.put("KEY", Fonts.KEY);
	unicodes.put("CLOSE_L", Fonts.CLOSE_L);
	unicodes.put("CONTROLER", Fonts.CONTROLER);
	unicodes.put("FIRE", Fonts.FIRE);
	unicodes.put("MOVABLE", Fonts.MOVABLE);
	unicodes.put("MORE", Fonts.MORE);
	unicodes.put("SORT1", Fonts.SORT1);
	unicodes.put("DESIGN", Fonts.DESIGN);
	unicodes.put("ON", Fonts.ON);
	unicodes.put("CLOSE1", Fonts.CLOSE1);
	unicodes.put("REMOVE", Fonts.REMOVE);
	unicodes.put("OFF", Fonts.OFF);
	unicodes.put("ZHONG", Fonts.ZHONG);
	unicodes.put("OPEN", Fonts.OPEN);
	unicodes.put("DEVELOPER", Fonts.DEVELOPER);
	unicodes.put("SCHEMA_PROPERTY", Fonts.SCHEMA_PROPERTY);
	unicodes.put("WARNING", Fonts.WARNING);
	unicodes.put("STYLE", Fonts.STYLE);
	unicodes.put("OVERVIEW", Fonts.OVERVIEW);
	unicodes.put("PRODUCT", Fonts.PRODUCT);
	unicodes.put("LAND", Fonts.LAND);
	unicodes.put("CHEMETRY", Fonts.CHEMETRY);
	unicodes.put("RESIDENT", Fonts.RESIDENT);
	unicodes.put("ROAD", Fonts.ROAD);
	unicodes.put("FIRE_ENERGY", Fonts.FIRE_ENERGY);
	unicodes.put("DAPENG", Fonts.DAPENG);
	unicodes.put("TANK", Fonts.TANK);
	unicodes.put("WEI_MINER", Fonts.WEI_MINER);
	unicodes.put("WATER_ENERGY", Fonts.WATER_ENERGY);
	unicodes.put("WATER_FARM", Fonts.WATER_FARM);
	unicodes.put("FE", Fonts.FE);
	unicodes.put("BUILDING", Fonts.BUILDING);
	unicodes.put("EME_TEXT", Fonts.EME_TEXT);
	unicodes.put("LABEL_MAKER", Fonts.LABEL_MAKER);
	unicodes.put("CONTRAST", Fonts.CONTRAST);
	unicodes.put("MODULE", Fonts.MODULE);
	unicodes.put("ALIGN_VERTICAL", Fonts.ALIGN_VERTICAL);
	unicodes.put("ALIGN_HORIZONTAL", Fonts.ALIGN_HORIZONTAL);
	unicodes.put("ALIGN_BOTTOM", Fonts.ALIGN_BOTTOM);
	unicodes.put("ALIGN_LEFT", Fonts.ALIGN_LEFT);
	unicodes.put("ALIGN_CENTER", Fonts.ALIGN_CENTER);
	unicodes.put("ALIGN_RIGHT", Fonts.ALIGN_RIGHT);
	unicodes.put("TEXT_WRAP", Fonts.TEXT_WRAP);
	unicodes.put("ALIGN_MIDDLE", Fonts.ALIGN_MIDDLE);
	unicodes.put("LIST", Fonts.LIST);
	unicodes.put("ALIGN_TOP", Fonts.ALIGN_TOP);
	unicodes.put("HELP", Fonts.HELP);
	unicodes.put("APPLICATION", Fonts.APPLICATION);
	unicodes.put("IMAGESTUDIO", Fonts.IMAGESTUDIO);
	unicodes.put("PLOTTING", Fonts.PLOTTING);
	unicodes.put("SCHEMA", Fonts.SCHEMA);
	unicodes.put("FLOW", Fonts.FLOW);
	unicodes.put("CLEAN_SAMPLE", Fonts.CLEAN_SAMPLE);
	unicodes.put("SAMPLE_PRODUCT", Fonts.SAMPLE_PRODUCT);
	unicodes.put("SAMPLE_PLOTTING", Fonts.SAMPLE_PLOTTING);
	unicodes.put("IMPORT_SAMPLE", Fonts.IMPORT_SAMPLE);
	unicodes.put("TOOLBOX", Fonts.TOOLBOX);
	unicodes.put("HYPERFRACTIONATION", Fonts.HYPERFRACTIONATION);
	unicodes.put("ENHANCE_COLOR", Fonts.ENHANCE_COLOR);
	unicodes.put("CLOUD_DETECTION", Fonts.CLOUD_DETECTION);
	unicodes.put("ORTHOPHOTO", Fonts.ORTHOPHOTO);
	unicodes.put("LAYOUT", Fonts.LAYOUT);
	unicodes.put("CREATE", Fonts.CREATE);
	unicodes.put("ADD_PROJECT", Fonts.ADD_PROJECT);
	unicodes.put("LAYER_MANAGEMENT", Fonts.LAYER_MANAGEMENT);
	unicodes.put("FAVORITE_ON", Fonts.FAVORITE_ON);
	unicodes.put("FAVORITE_OFF", Fonts.FAVORITE_OFF);
	unicodes.put("TRAININGSTUDIO", Fonts.TRAININGSTUDIO);
	unicodes.put("MAPSTUDIO", Fonts.MAPSTUDIO);
	unicodes.put("LABELFACTORY", Fonts.LABELFACTORY);
	unicodes.put("AISTUDIO", Fonts.AISTUDIO);
	unicodes.put("ADMIN", Fonts.ADMIN);
	unicodes.put("GRID", Fonts.GRID);
	unicodes.put("EARTH", Fonts.EARTH);
	unicodes.put("LINK", Fonts.LINK);
	unicodes.put("WRITE", Fonts.WRITE);
	unicodes.put("READ", Fonts.READ);
	unicodes.put("VISIBILITY", Fonts.VISIBILITY);
	unicodes.put("HIDDEN", Fonts.HIDDEN);
	unicodes.put("PALETTE", Fonts.PALETTE);
	unicodes.put("RETURN", Fonts.RETURN);
	unicodes.put("TERMINAL", Fonts.TERMINAL);
	unicodes.put("SHARE", Fonts.SHARE);
	unicodes.put("LOG", Fonts.LOG);
	unicodes.put("TASK", Fonts.TASK);
	unicodes.put("FEATURE", Fonts.FEATURE);
	unicodes.put("OBJECT", Fonts.OBJECT);
	unicodes.put("MODEL", Fonts.MODEL);
	unicodes.put("ROLL", Fonts.ROLL);
	unicodes.put("LAYERS", Fonts.LAYERS);
	unicodes.put("MAP_ADD", Fonts.MAP_ADD);
	unicodes.put("DELETE", Fonts.DELETE);
	unicodes.put("LOCATION", Fonts.LOCATION);
	unicodes.put("RESET", Fonts.RESET);
	unicodes.put("CATALOG_ADD", Fonts.CATALOG_ADD);
	unicodes.put("COMPARE", Fonts.COMPARE);
	unicodes.put("LEGEND", Fonts.LEGEND);
	unicodes.put("CERT", Fonts.CERT);
	unicodes.put("METADATA", Fonts.METADATA);
	unicodes.put("K8S", Fonts.K8S);
	unicodes.put("SAVE", Fonts.SAVE);
	unicodes.put("LOGO", Fonts.LOGO);
	unicodes.put("PROCESS", Fonts.PROCESS);
	unicodes.put("CANGLING_TEXT", Fonts.CANGLING_TEXT);
	unicodes.put("GEOSERVER", Fonts.GEOSERVER);
	unicodes.put("LABEL", Fonts.LABEL);
	unicodes.put("LIGHTMODE", Fonts.LIGHTMODE);
	unicodes.put("DARKMODE", Fonts.DARKMODE);
	unicodes.put("GEOTRELLIS", Fonts.GEOTRELLIS);
	unicodes.put("FOLDER_FILE", Fonts.FOLDER_FILE);
	unicodes.put("PLAY", Fonts.PLAY);
	unicodes.put("PAUSE", Fonts.PAUSE);
	unicodes.put("FILES", Fonts.FILES);
	unicodes.put("IMAGES", Fonts.IMAGES);
	unicodes.put("CLEAR_CACHE", Fonts.CLEAR_CACHE);
	unicodes.put("ALERT", Fonts.ALERT);
	unicodes.put("SFILE", Fonts.SFILE);
	unicodes.put("FOLDER", Fonts.FOLDER);
	unicodes.put("FILE", Fonts.FILE);
	unicodes.put("LEFT", Fonts.LEFT);
	unicodes.put("RIGHT", Fonts.RIGHT);
	unicodes.put("DOWN", Fonts.DOWN);
	unicodes.put("UP", Fonts.UP);
	unicodes.put("REFRESH", Fonts.REFRESH);
	unicodes.put("INFO", Fonts.INFO);
	unicodes.put("COLORS", Fonts.COLORS);
	unicodes.put("CLEAR", Fonts.CLEAR);
	unicodes.put("DONE", Fonts.DONE);
	unicodes.put("FULL_SCREEN", Fonts.FULL_SCREEN);
	unicodes.put("HARBOR", Fonts.HARBOR);
	unicodes.put("PLUS", Fonts.PLUS);
	unicodes.put("UPLOAD", Fonts.UPLOAD);
	unicodes.put("DOWNLOAD", Fonts.DOWNLOAD);
	unicodes.put("DOUBLE_LEFT", Fonts.DOUBLE_LEFT);
	unicodes.put("DOUBLE_RIGHT", Fonts.DOUBLE_RIGHT);
	unicodes.put("FINANCIAL_HARD_DISK", Fonts.FINANCIAL_HARD_DISK);
	unicodes.put("SEARCH", Fonts.SEARCH);
	unicodes.put("SETTING", Fonts.SETTING);
	unicodes.put("CONSOLE", Fonts.CONSOLE);

	}
}
